package app.turattext.mobile.ui

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Палитра оформления Turat. Экраны читают цвета только отсюда, поэтому новая тема — это одна
 * запись в [AppTheme], а не правки в разметке.
 */
@Immutable
data class TuratPalette(
    /** Тёмная тема: от этого зависят светлые значки системных панелей. */
    val night: Boolean,
    val window: Color,
    val panel: Color,
    val elevated: Color,
    val field: Color,
    val divider: Color,
    val text: Color,
    val hint: Color,
    val accent: Color,
    /** Текст и значки поверх акцентной заливки: у светлых акцентов он тёмный. */
    val onAccent: Color,
    val accentSoft: Color,
    val chatTop: Color,
    val chatBottom: Color,
    val bubbleIn: Color,
    val bubbleOut: Color,
    val bubbleInText: Color,
    val bubbleOutText: Color,
    val bubbleInMeta: Color,
    val bubbleOutMeta: Color,
    val tick: Color,
    val servicePill: Color,
    val serviceText: Color,
    val badge: Color,
    val badgeMuted: Color,
    val badgeText: Color,
    val online: Color,
    val danger: Color,
    val rowActive: Color,
    val selection: Color,
)

private val OriginPalette = TuratPalette(
    night = true,
    window = Color(0xFF1C1C1C),
    panel = Color(0xFF1C1C1C),
    elevated = Color(0xFF242424),
    field = Color(0xFF2B2B2B),
    divider = Color(0xFF353535),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFF9A9A9A),
    accent = Color(0xFFC9354A),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0xFF572832),
    chatTop = Color(0xFF1C1C1C),
    chatBottom = Color(0xFF211B1C),
    bubbleIn = Color(0xFF292929),
    bubbleOut = Color(0xFFC9354A),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFFFFFFFF),
    bubbleInMeta = Color(0xFF969696),
    bubbleOutMeta = Color(0xFFFFD7DD),
    tick = Color(0xFFFFD7DD),
    servicePill = Color(0xCC242424),
    serviceText = Color(0xFFB5B5B5),
    badge = Color(0xFFC9354A),
    badgeMuted = Color(0xFF5C5C5C),
    badgeText = Color(0xFFFFFFFF),
    online = Color(0xFF4CCC5E),
    danger = Color(0xFFEC6A65),
    rowActive = Color(0xFF572832),
    selection = Color(0x40C9354A),
)

private val GarnetPalette = TuratPalette(
    night = true,
    window = Color(0xFF1F0D12),
    panel = Color(0xFF241016),
    elevated = Color(0xFF2E151D),
    field = Color(0xFF381A23),
    divider = Color(0xFF44212B),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFFB4909C),
    accent = Color(0xFFD93E5C),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0xFF5C2130),
    chatTop = Color(0xFF1F0D12),
    chatBottom = Color(0xFF2A1119),
    bubbleIn = Color(0xFF2E151D),
    bubbleOut = Color(0xFFD93E5C),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFFFFFFFF),
    bubbleInMeta = Color(0xFFAD8894),
    bubbleOutMeta = Color(0xFFFFD8E0),
    tick = Color(0xFFFFD8E0),
    servicePill = Color(0xCC2E151D),
    serviceText = Color(0xFFC5A5AF),
    badge = Color(0xFFD93E5C),
    badgeMuted = Color(0xFF6B4550),
    badgeText = Color(0xFFFFFFFF),
    online = Color(0xFF4CCC5E),
    danger = Color(0xFFFF8A80),
    rowActive = Color(0xFF5C2130),
    selection = Color(0x40D93E5C),
)

private val ObsidianPalette = TuratPalette(
    night = true,
    window = Color(0xFF0F1626),
    panel = Color(0xFF131C2F),
    elevated = Color(0xFF1A2440),
    field = Color(0xFF1F2B4A),
    divider = Color(0xFF283557),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFF8E9BBA),
    accent = Color(0xFF3B6FE0),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0xFF23355F),
    chatTop = Color(0xFF0F1626),
    chatBottom = Color(0xFF141D33),
    bubbleIn = Color(0xFF1B2542),
    bubbleOut = Color(0xFF3B6FE0),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFFFFFFFF),
    bubbleInMeta = Color(0xFF8C9AB8),
    bubbleOutMeta = Color(0xFFD3E1FF),
    tick = Color(0xFFD3E1FF),
    servicePill = Color(0xCC1A2440),
    serviceText = Color(0xFFA7B4CE),
    badge = Color(0xFF3B6FE0),
    badgeMuted = Color(0xFF4A5670),
    badgeText = Color(0xFFFFFFFF),
    online = Color(0xFF3ECF7E),
    danger = Color(0xFFF2766B),
    rowActive = Color(0xFF23355F),
    selection = Color(0x403B6FE0),
)

private val BlackPalette = TuratPalette(
    night = true,
    window = Color(0xFF000000),
    panel = Color(0xFF0A0A0A),
    elevated = Color(0xFF141414),
    field = Color(0xFF1B1B1B),
    divider = Color(0xFF262626),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFF8C8C8C),
    accent = Color(0xFFE6E6E6),
    onAccent = Color(0xFF0A0A0A),
    accentSoft = Color(0xFF2A2A2A),
    chatTop = Color(0xFF000000),
    chatBottom = Color(0xFF050505),
    bubbleIn = Color(0xFF171717),
    bubbleOut = Color(0xFFE6E6E6),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFF0A0A0A),
    bubbleInMeta = Color(0xFF8C8C8C),
    bubbleOutMeta = Color(0xFF565656),
    tick = Color(0xFF565656),
    servicePill = Color(0xCC171717),
    serviceText = Color(0xFFB0B0B0),
    badge = Color(0xFFE6E6E6),
    badgeMuted = Color(0xFF4A4A4A),
    badgeText = Color(0xFF0A0A0A),
    online = Color(0xFF4CCC5E),
    danger = Color(0xFFFF6B60),
    rowActive = Color(0xFF232323),
    selection = Color(0x33FFFFFF),
)

private val GraphitePalette = TuratPalette(
    night = true,
    window = Color(0xFF1C242C),
    panel = Color(0xFF202932),
    elevated = Color(0xFF29343F),
    field = Color(0xFF2F3B47),
    divider = Color(0xFF394653),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFF9AAAB8),
    accent = Color(0xFF6E93B8),
    onAccent = Color(0xFF0D1720),
    accentSoft = Color(0xFF31465A),
    chatTop = Color(0xFF1C242C),
    chatBottom = Color(0xFF212B35),
    bubbleIn = Color(0xFF29343F),
    bubbleOut = Color(0xFF6E93B8),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFF0D1720),
    bubbleInMeta = Color(0xFF94A4B2),
    bubbleOutMeta = Color(0xFF2B4055),
    tick = Color(0xFF2B4055),
    servicePill = Color(0xCC29343F),
    serviceText = Color(0xFFB0BECA),
    badge = Color(0xFF6E93B8),
    badgeMuted = Color(0xFF4A5A68),
    badgeText = Color(0xFF0D1720),
    online = Color(0xFF48C77A),
    danger = Color(0xFFF07A6E),
    rowActive = Color(0xFF31465A),
    selection = Color(0x406E93B8),
)

private val EmeraldPalette = TuratPalette(
    night = true,
    window = Color(0xFF05231D),
    panel = Color(0xFF072A23),
    elevated = Color(0xFF0B372E),
    field = Color(0xFF104338),
    divider = Color(0xFF175143),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFF8DB6AA),
    accent = Color(0xFF0F9D6F),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0xFF13503E),
    chatTop = Color(0xFF05231D),
    chatBottom = Color(0xFF082B23),
    bubbleIn = Color(0xFF0B372E),
    bubbleOut = Color(0xFF0F9D6F),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFFFFFFFF),
    bubbleInMeta = Color(0xFF8AAFA4),
    bubbleOutMeta = Color(0xFFCDF3E4),
    tick = Color(0xFFCDF3E4),
    servicePill = Color(0xCC0B372E),
    serviceText = Color(0xFFA5C9BF),
    badge = Color(0xFF0F9D6F),
    badgeMuted = Color(0xFF3F6459),
    badgeText = Color(0xFFFFFFFF),
    online = Color(0xFF3FD98C),
    danger = Color(0xFFF0796C),
    rowActive = Color(0xFF13503E),
    selection = Color(0x400F9D6F),
)

private val OceanPalette = TuratPalette(
    night = true,
    window = Color(0xFF06222F),
    panel = Color(0xFF082938),
    elevated = Color(0xFF0C3547),
    field = Color(0xFF104155),
    divider = Color(0xFF174F65),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFF89AABB),
    accent = Color(0xFF1E8FC4),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0xFF124D66),
    chatTop = Color(0xFF06222F),
    chatBottom = Color(0xFF082A39),
    bubbleIn = Color(0xFF0C3547),
    bubbleOut = Color(0xFF1E8FC4),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFFFFFFFF),
    bubbleInMeta = Color(0xFF87A5B6),
    bubbleOutMeta = Color(0xFFCDEBFA),
    tick = Color(0xFFCDEBFA),
    servicePill = Color(0xCC0C3547),
    serviceText = Color(0xFFA2C1D2),
    badge = Color(0xFF1E8FC4),
    badgeMuted = Color(0xFF3D6274),
    badgeText = Color(0xFFFFFFFF),
    online = Color(0xFF3FD08C),
    danger = Color(0xFFF0796C),
    rowActive = Color(0xFF124D66),
    selection = Color(0x401E8FC4),
)

private val AmberPalette = TuratPalette(
    night = true,
    window = Color(0xFF241407),
    panel = Color(0xFF2B190A),
    elevated = Color(0xFF382110),
    field = Color(0xFF442915),
    divider = Color(0xFF52331C),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFFBBA189),
    accent = Color(0xFFD98324),
    onAccent = Color(0xFF1C0F02),
    accentSoft = Color(0xFF5C3714),
    chatTop = Color(0xFF241407),
    chatBottom = Color(0xFF2C1A0B),
    bubbleIn = Color(0xFF382110),
    bubbleOut = Color(0xFFD98324),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFF1C0F02),
    bubbleInMeta = Color(0xFFB49A82),
    bubbleOutMeta = Color(0xFF56320C),
    tick = Color(0xFF56320C),
    servicePill = Color(0xCC382110),
    serviceText = Color(0xFFC9B39C),
    badge = Color(0xFFD98324),
    badgeMuted = Color(0xFF6B5238),
    badgeText = Color(0xFF1C0F02),
    online = Color(0xFF5CC96B),
    danger = Color(0xFFF57F6C),
    rowActive = Color(0xFF5C3714),
    selection = Color(0x40D98324),
)

private val AmethystPalette = TuratPalette(
    night = true,
    window = Color(0xFF1B1030),
    panel = Color(0xFF201438),
    elevated = Color(0xFF2A1B49),
    field = Color(0xFF332158),
    divider = Color(0xFF3D2968),
    text = Color(0xFFFFFFFF),
    hint = Color(0xFFA595C4),
    accent = Color(0xFF8B5CF6),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0xFF3B2670),
    chatTop = Color(0xFF1B1030),
    chatBottom = Color(0xFF211539),
    bubbleIn = Color(0xFF2A1B49),
    bubbleOut = Color(0xFF8B5CF6),
    bubbleInText = Color(0xFFFFFFFF),
    bubbleOutText = Color(0xFFFFFFFF),
    bubbleInMeta = Color(0xFFA294BE),
    bubbleOutMeta = Color(0xFFE4D8FF),
    tick = Color(0xFFE4D8FF),
    servicePill = Color(0xCC2A1B49),
    serviceText = Color(0xFFBAABD6),
    badge = Color(0xFF8B5CF6),
    badgeMuted = Color(0xFF574A73),
    badgeText = Color(0xFFFFFFFF),
    online = Color(0xFF4CD07F),
    danger = Color(0xFFF4796F),
    rowActive = Color(0xFF3B2670),
    selection = Color(0x408B5CF6),
)

private val CloudPalette = TuratPalette(
    night = false,
    window = Color(0xFFEEF2FB),
    panel = Color(0xFFFFFFFF),
    elevated = Color(0xFFFFFFFF),
    field = Color(0xFFE7ECF7),
    divider = Color(0xFFD8DFEF),
    text = Color(0xFF16202E),
    hint = Color(0xFF6A7A90),
    accent = Color(0xFF2563EB),
    onAccent = Color(0xFFFFFFFF),
    accentSoft = Color(0xFFD6E2FB),
    chatTop = Color(0xFFEEF2FB),
    chatBottom = Color(0xFFE5ECF9),
    bubbleIn = Color(0xFFFFFFFF),
    bubbleOut = Color(0xFF2563EB),
    bubbleInText = Color(0xFF16202E),
    bubbleOutText = Color(0xFFFFFFFF),
    bubbleInMeta = Color(0xFF8494A8),
    bubbleOutMeta = Color(0xFFCBDDFF),
    tick = Color(0xFFCBDDFF),
    servicePill = Color(0xE6DCE5F5),
    serviceText = Color(0xFF5C6B80),
    badge = Color(0xFF2563EB),
    badgeMuted = Color(0xFFA6B2C4),
    badgeText = Color(0xFFFFFFFF),
    online = Color(0xFF1F9D55),
    danger = Color(0xFFD93025),
    rowActive = Color(0xFFD6E2FB),
    selection = Color(0x332563EB),
)

private val ParchmentPalette = TuratPalette(
    night = false,
    window = Color(0xFFF2EADA),
    panel = Color(0xFFFBF5E9),
    elevated = Color(0xFFFBF5E9),
    field = Color(0xFFEDE3D0),
    divider = Color(0xFFDED0B6),
    text = Color(0xFF2E2418),
    hint = Color(0xFF7C6C55),
    accent = Color(0xFF96683A),
    onAccent = Color(0xFFFFF8EC),
    accentSoft = Color(0xFFE4D6BC),
    chatTop = Color(0xFFF2EADA),
    chatBottom = Color(0xFFEDE2CE),
    bubbleIn = Color(0xFFFBF5E9),
    bubbleOut = Color(0xFF96683A),
    bubbleInText = Color(0xFF2E2418),
    bubbleOutText = Color(0xFFFFF8EC),
    bubbleInMeta = Color(0xFF9C8A70),
    bubbleOutMeta = Color(0xFFE7D3BB),
    tick = Color(0xFFE7D3BB),
    servicePill = Color(0xE6E6DAC2),
    serviceText = Color(0xFF6E5E48),
    badge = Color(0xFF96683A),
    badgeMuted = Color(0xFFB7A88F),
    badgeText = Color(0xFFFFF8EC),
    online = Color(0xFF4E8A3C),
    danger = Color(0xFFB3381F),
    rowActive = Color(0xFFE4D6BC),
    selection = Color(0x3396683A),
)

/** Тема оформления: подпись в настройках и её палитра. */
enum class AppTheme(val title: String, val palette: TuratPalette) {
    Origin("Ориджин", OriginPalette),
    Garnet("Гранат", GarnetPalette),
    Obsidian("Обсидиан", ObsidianPalette),
    Black("Чёрный", BlackPalette),
    Graphite("Графит", GraphitePalette),
    Emerald("Изумрудный", EmeraldPalette),
    Ocean("Океан", OceanPalette),
    Amber("Янтарь", AmberPalette),
    Amethyst("Аметист", AmethystPalette),
    Cloud("Облачный", CloudPalette),
    Parchment("Пергамент", ParchmentPalette);

    companion object {
        /** Неизвестное значение из настроек прежних версий приводит к фирменной теме. */
        fun parse(value: String?): AppTheme = entries.firstOrNull { it.name == value } ?: Origin
    }
}

val LocalTurat = staticCompositionLocalOf { AppTheme.Origin.palette }

object Telegram {
    val colors: TuratPalette
        @Composable @ReadOnlyComposable get() = LocalTurat.current
}

@Composable
fun TuratTextTheme(theme: AppTheme = AppTheme.Origin, content: @Composable () -> Unit) {
    val palette = theme.palette
    val scheme = if (palette.night) {
        darkColorScheme(
            primary = palette.accent,
            onPrimary = palette.onAccent,
            secondary = palette.accent,
            onSecondary = palette.onAccent,
            background = palette.window,
            onBackground = palette.text,
            surface = palette.elevated,
            onSurface = palette.text,
            surfaceVariant = palette.field,
            onSurfaceVariant = palette.hint,
            outline = palette.divider,
            error = palette.danger,
        )
    } else {
        lightColorScheme(
            primary = palette.accent,
            onPrimary = palette.onAccent,
            secondary = palette.accent,
            onSecondary = palette.onAccent,
            background = palette.window,
            onBackground = palette.text,
            surface = palette.elevated,
            onSurface = palette.text,
            surfaceVariant = palette.field,
            onSurfaceVariant = palette.hint,
            outline = palette.divider,
            error = palette.danger,
        )
    }
    CompositionLocalProvider(LocalTurat provides palette) {
        MaterialTheme(colorScheme = scheme, typography = Typography(), content = content)
    }
}
