create table v2_mailboxes (
    id uuid primary key,
    read_capability_hash varchar(64) not null unique,
    write_capability_hash varchar(64) not null unique,
    device_hint varchar(160) not null,
    created_at timestamptz not null,
    expires_at timestamptz not null
);

create index ix_v2_mailboxes_expiry on v2_mailboxes (expires_at);

create table v2_envelopes (
    id varchar(100) primary key,
    mailbox_id uuid not null references v2_mailboxes(id) on delete cascade,
    protocol_version integer not null,
    recipient_device_hint varchar(160),
    opaque_payload text not null,
    size_class integer not null,
    created_at timestamptz not null,
    expires_at timestamptz not null,
    received_at timestamptz not null
);

create index ix_v2_envelopes_mailbox_received
    on v2_envelopes (mailbox_id, received_at, id);
create index ix_v2_envelopes_expiry on v2_envelopes (expires_at);

create table v2_prekey_bundles (
    mailbox_id uuid primary key references v2_mailboxes(id) on delete cascade,
    user_id varchar(80) not null,
    device_id varchar(90) not null,
    identity_json text not null,
    signed_prekey_json text not null,
    sequence_number bigint not null,
    expires_at timestamptz not null,
    updated_at timestamptz not null,
    unique (user_id, device_id)
);

create table v2_one_time_prekeys (
    id uuid primary key,
    mailbox_id uuid not null references v2_mailboxes(id) on delete cascade,
    prekey_id varchar(100) not null,
    prekey_json text not null,
    created_at timestamptz not null,
    unique (mailbox_id, prekey_id)
);

create index ix_v2_one_time_prekeys_mailbox
    on v2_one_time_prekeys (mailbox_id, created_at);

create table v2_routing_records (
    user_id varchar(80) primary key,
    identity_public_key text not null,
    sequence_number bigint not null,
    descriptor_json text not null,
    signature text not null,
    expires_at timestamptz not null,
    updated_at timestamptz not null
);

create index ix_v2_routing_records_expiry on v2_routing_records (expires_at);

create table v2_transparency_operations (
    sequence_number bigint generated by default as identity primary key,
    operation_id varchar(100) not null unique,
    operation_type varchar(50) not null,
    subject_id varchar(100) not null,
    payload_hash varchar(64) not null,
    payload text not null,
    signature text not null,
    created_at timestamptz not null
);

create index ix_v2_transparency_subject
    on v2_transparency_operations (subject_id, sequence_number);

create table v2_blob_objects (
    id varchar(100) primary key,
    read_capability_hash varchar(64) not null unique,
    write_capability_hash varchar(64) not null unique,
    expected_size bigint not null,
    chunk_size integer not null,
    created_at timestamptz not null,
    expires_at timestamptz not null
);

create index ix_v2_blob_objects_expiry on v2_blob_objects (expires_at);

create table v2_blob_chunks (
    object_id varchar(100) not null references v2_blob_objects(id) on delete cascade,
    chunk_index integer not null,
    ciphertext text not null,
    digest varchar(64) not null,
    size_bytes integer not null,
    created_at timestamptz not null,
    primary key (object_id, chunk_index)
);
